ansible.cfg, scripts/lib/ansible-executor.sh
Fix loosing SSH connection on building with docker-compose.
=> Unreachable 3

playbooks/group_vars/webportals.yml, playbooks/tasks/lastpass-load-webportal-cluster-config.yml, playbooks/tasks/lastpass-load-webportal-common-config.yml, playbooks/tasks/lastpass-load-webportal-server-config.yml, playbooks/tasks/lastpass-save-webportal-config.yml
This is a minor preparation for full `.env` generation by Ansible.
=> Rename and move lastpass/ansible configs

playbooks/templates/.env.j2
Quick fix to generate `PORTAL_DOMAIN` and `SERVER_DOMAIN` for portal setup.
Full `.env` generation from template and LastPass data is in progress
and will be in upcoming PR.
=> Update .env template with PORTAL_DOMAIN and SERVER_DOMAIN

playbooks/portals-setup-initial.yml
Fixed `portal-setup-initial` for `root` user by loading LastPass data.
=> Fix portal setup initial with getting LastPass data

playbooks/tasks/portal-firewall-ufw-setup.yml
=> Install ufw

playbooks/tasks/portal-health-check-disable.yml
=> Add health check message

playbooks/group_vars/webportals.yml
=> Update LastPass directories

playbooks/x-portals-setup-serverlist.yml
the server list playbook was broken because it referenced an old file name.
=> Fix server list task reference

changelog/items/other/playbook-template.md, playbooks/templates/playbook.yml
To help with others getting started with Ansible, I added a little template playbook file. 
=> refactor out of template playbook

changelog/items/key-updates/download-check.md, playbooks/group_vars/webportals_dev.yml, playbooks/group_vars/webportals_prod.yml, playbooks/tasks/portal-health-check-disable.yml
Add download check to health check disable task
=> Update health check disabling to check for downloads as well

changelog/items/key-updates/generate-env-with-mongo-accounts.md, playbooks/group_vars/webportals.yml, playbooks/tasks/portal-configs-get.yml, playbooks/tasks/portal-docker-compose-files-get-wanted.yml, playbooks/tasks/portal-role-task.yml, playbooks/templates/.env.j2
This PR updates `.env` file generation with MongoDB and Accounts settings.
=> Portal setup 4 - generate .env with MongoDB, Accounts settings

playbooks/templates/.env.j2
Update `SKYNET_ACCOUNTS_LOG_LEVEL` value in `.env` from `trace` to `info`.
=> Update accounts log level

playbooks/portals-deploy.yml
Found small bug as it relates to the allowance code.
=> fix bug with undefined update_allowance

changelog/items/other/ensure-latest-docker.md, playbooks/tasks/portal-setup-server.yml, playbooks/x-portals-ensure-latest-docker.yml, scripts/x-portals-ensure-latest-docker.sh
Add playbook to ensure the latest Docker engine server is used.
=> Add ensure latest docker playbook

changelog/items/other/airtable-env-vars.md, playbooks/templates/.env.j2
Moved Airtable variables to common config (LastPass) so that portal operators can easily use their own values.
#
=> Add Airtable vars to .env

playbooks/tasks/portal-setup-server.yml
We need to install `libffi-dev` as a required dependency for pip3 docker-compose.
=> Install libffi-dev as a pip3 docker-compose dependency

requirements.yml
Update docker Ansible role to 4.1.1.
=> Update docker role to 4.1.1

README.md, changelog/items/other/auto-requirements.md, scripts/install-ansible-roles-and-collections.sh, scripts/lib/ansible-executor.sh
Previously Ansible roles and collections had to be installed manually.
This PR handles this automatically, installing and updating roles and collections automatically on each machine when needed.
=> Install Ansible roles and collections automatically

playbooks/tasks/portal-docker-compose-files-get-wanted.yml, playbooks/templates/.env.j2
Quote `.env` vars with spaces or special characters (e.g. '(') causing playbook issues.
=> Quote .env vars with special chars or spaces

README.md, changelog/items/other/block-malicious-ip-ranges.md, playbooks/group_vars/webportals.yml, playbooks/portals-block-unblock-incoming-traffic.yml, playbooks/portals-setup-following.yml, playbooks/tasks/portal-firewall-iptables-block-unblock.yml, playbooks/tasks/portal-firewall-setup.yml, playbooks/tasks/portal-firewall-ufw-setup.yml, scripts/portals-block-unblock-incoming-traffic.sh
Block malicious IP ranges with ufw firewall. The list of IP ranges is stored in `ansible-private` repository.
=> Block ip ranges

changelog/items/other/increase-ufw-ssh-limits.md, playbooks/tasks/portal-firewall-ufw-setup.yml
Increase ufw ssh limits to 60 hits in 30 seconds.
=> Increase ufw ssh limits

changelog/items/key-updates/support-blocker-module.md, playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
Add support to Blocker portal module to portal deploments, restarts.
=> Add support for Blocker module

changelog/items/other/mke-server-domain-mandatory.md, playbooks/templates/.env.j2
Update `.env` file generation with now mandatory `SERVER_DOMAIN` and new `ACCOUNTS_EMAIL_URI`.
=> Update .env file generation

changelog/items/bugs-fixed/hosts-limit-zero-check.md, playbooks/tasks/host-limit-check.yml
The hosts limit check wasn't properly handling the case when there is just one host. 
=> Add 0 check for max hosts

playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
Rename email variable to be generic for portal operators.
=> rename email variable to be generic for portal operators

my-vars/config-sample-do-not-edit.yml
Added the new email variables to the config.yml example.
Also updated the `ansible-private-sample` repo to remove the email defined in hosts.ini.
=> Add emails to config sample

changelog/items/other/generate-env-blocker-abuse-scanner.md, changelog/items/other/remove-cockroach-env-vars.md, changelog/items/other/remove-domain-name.md, playbooks/tasks/portal-configs-get.yml, playbooks/templates/.env.j2
Add generation of Blocker and Abuse Scanner variables in `.env` file.
Closes #191
Closes #190
Closes #101
=> Generate .env vars for Blocker, Abuse Scanner

changelog/items/other/create-lastpass-user-password.md, my-vars/config-sample-do-not-edit.yml, playbooks/group_vars/webportals.yml, playbooks/portals-setup-initial.yml, playbooks/tasks/lastpass-save-user-credentials.yml
Create webportal user password and save it to LastPass automatically if it is not yet present in LastPass.
=> Create webportal user password and save it to LastPass automatically

changelog/items/other/accounts-limit-access.md, playbooks/templates/.env.j2
Update `.env` generation with `ACCOUNTS_LIMIT_ACCESS`.
=> Accounts limit access

playbooks/group_vars/webportals.yml, playbooks/tasks/lastpass-load-json-note.yml, playbooks/tasks/lastpass-load-webportal-config.yml, playbooks/tasks/lastpass-load-yaml-note.yml, playbooks/tasks/portal-role-task.yml
This PR adds auto generation for the COOKIE variables and loads the JWKS file from LastPass. 
Tested on personal portal.
=> COOKIES and JWKS for accounts

playbooks/portals-takedown.yml
Simple `portal_action` variable undefined bug fix.
=> Fix undefined portal_actions bug

playbooks/group_vars/webportals.yml, playbooks/tasks/portal-configs-get.yml, playbooks/templates/.env.j2
Clean up .env file, move all defaults to `playbooks/group_vars/webportals.yml` and only have hardcoded values and blanks in the `.env` file. Update comments to reflect changes.
=> Clean up .env File

changelog/items/other/block-ip-parallel.md, playbooks/portals-block-unblock-incoming-traffic.yml
Speed up blocking incoming IPs/ranges by running in parallel.
=> Speed up blocking incoming traffic by parallel execution

playbooks/tasks/portal-docker-services-start.yml
tested on previous release, works fine
=> do not disable docker cache on builds

playbooks/templates/.env.j2
Super small clarifying comment as I missed it on first pass.
=> minor comment update

changelog/items/other/integration-tests-cookie.md, playbooks/tasks/portal-integration-tests-run.yml
Use authentication cookie for integration tests on non-anonymous portals.
=> Add auth cookie for integration tests

playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
follow up for https://github.com/SkynetLabs/skynet-webportal/pull/1722 (wait until it's merged)
=> remove portal name env var

playbooks/tasks/portal-role-task.yml
Fix failing playbook on allowance update.
=> Fix update allowance check

playbooks/group_vars/webportals.yml, playbooks/tasks/portal-docker-compose-files-get-wanted.yml
rename abuse to abuse-scanner
depends on https://github.com/SkynetLabs/skynet-webportal/pull/1766
=> rename abuse to abuse-scanner

playbooks/templates/.env.j2
follow up to https://github.com/SkynetLabs/skynet-webportal/pull/1727
=> remove SKYNET_PORTAL_API and SKYNET_SERVER_API

changelog/items/key-updates/tor-exit-node-block.md, playbooks/x-portals-block-tor-exit-nodes.yml, scripts/x-portals-block-tor-exit-nodes.sh
PR with a playbook to block Tor exit node traffic.
- This is a quick fix playbook, needs to be triggered manually (playbook execution).
- Periodic job to load blocklists will be done in a separate PR.
=> Block to exit

changelog/items/other/serverlist-v004.md, playbooks/x-portals-setup-serverlist.yml
Update serverlist version to handle removed env vars.
=> Update serverlist version to v0.0.4

changelog/items/key-updates/add-debian-11-support.md, playbooks/all-docker-install.yml, playbooks/deploy-machines-setup.yml, playbooks/dev-machines-setup-and-secure.yml, playbooks/portals-setup-following.yml, playbooks/portals-setup-initial.yml, playbooks/tasks/check-server-os-compatibility.yml, requirements.yml
=> add debian 11 compatibility

playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
https://discord.com/channels/542938080349519882/943125167410913320/943145266477944842
=> Add a field for specifying a test user API key.

playbooks/templates/.env.j2
The `ABUSE_MAILBOX` needs to be configurable through ansible and defined by the user.
N/A
N/A
=> Extend Ansible Variables

changelog/items/key-updates/support-ubuntu.md, playbooks/tasks/check-server-os-compatibility.yml, requirements.yml
Miraculously we now support also Ubuntu 20.04.
- deploys are working already a couple of months
- `portal-setup-following` finished today ok
=> Add Ubuntu support

changelog/items/other/tor-blocklist-comment.md, playbooks/group_vars/webportals.yml
Update comment on Tor blocklist root cron job script.
Closes #241
=> Update Tor blocklist redownload comment

README.md
Minor Doc update for portal ping.
=> Update portal ping documentation

changelog/items/other/install-python3.md, playbooks/portals-setup-initial.yml
Some minimal fresh OS installs do not have installed Python3 required by Ansible. This PR installs `python3` package on the host if it is not installed.
=> Install Python3 for Ansible on the fresh server

changelog/items/other/add-blocker-sync-portals-env.md, playbooks/templates/.env.j2
This PR adds a dynamic variable to update the env variable `BLOCKER_PORTALS_SYNC`.
It also cleans up some unused variables.
N/A
N/A
=> Update blocker config

changelog/items/key-updates/domain-consolidation.md, playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
This PR consolidates the use of all the domains and utilizes this update https://github.com/SkynetLabs/ansible-private-sample/blob/main/inventory/hosts.ini#L19
Now users can just define domains in the hosts.ini file and won't need define anything in LastPass ahead of time. 
=> consolidate use of server, cluster, and portal domain

playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
Update how backwards compatibility is handled with portal_modules.
=> move portal modules outside of server config

.ansible-lint, .yamllint.yml
Fix some yamllint warnings from the github action.
=> Fix yamllint errors

playbooks/templates/.env.j2
Fix reading portal domain from LastPass.
=> Fix cluster domain

changelog/items/other/add-reporting-env-vars.md, playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
This PR adds the necessary environment variables for the reporting feature.
N/A
N/A
=> Reporting Env Variables

changelog/items/bugs-fixed/fix-mongo-mgkey.md, playbooks/tasks/portal-configs-load.yml
A minor, but important (critical) fix to auto-generating MongoDB mgkey.
=> Fix setting MongoDB mgkey

playbooks/tasks/portal-versions-set.yml
Add missing assert condition to allow neither option being set.
=> Add missing assert condition

changelog/items/other/remove-auth-cookie.md, playbooks/tasks/portal-integration-tests-run.yml
Removed authentication cookie from running integration tests, as it is obsolete (we use API key now) and it has never worked.
=> Remove authentication cookie

ansible.cfg, changelog/items/other/task-execution-times.md, requirements.yml
=> Log task execution times

playbooks/deploy-machines-setup.yml, playbooks/tasks/portal-role-task.yml, playbooks/tasks/portal-setup-server.yml, playbooks/tasks/portals-prepare.yml
- pin specific versions of packages instead of using latest
- also according to [ansible pip docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) we don't need to define loop, we can just define a number of packages we want installed
=> pin pip package versions

changelog/items/bugs-fixed/fix-setting-accounts.md, playbooks/group_vars/webportals.yml, playbooks/tasks/portal-role-task.yml, playbooks/tasks/portal-versions-set.yml, playbooks/templates/docker-compose.override.yml.final.j2
Fix deployments after Accounts services dropped build context from `docker-compose.accounts.yml`.
=> Fix deployments issue caused by updated  Accounts

changelog/items/bugs-fixed/fix-elasticsearch-permissions.md, playbooks/tasks/portal-role-task.yml
Fix `elasticsearch` container data permissions recursively to prevent container restarting.
=> SKY-145 Fix elasticsearch permissions

changelog/items/key-updates/execute-commands.md, playbooks/tasks/portal-deploy-enable-loadbalancer.yml, playbooks/tasks/portal-docker-services-start.yml, playbooks/tasks/portal-execute-commands.yml
Refactor executing any one off or long term commands into starting docker services instead of enabling the load balancer. These ensures that when new portals are set up, they include any necessary commands such as blocking hosts before they are in production.
Closes SKY-283
=> Add execute commands task

changelog/items/bugs-fixed/fix-blocked-unblock-doamins.md, playbooks/tasks/portal-execute-commands.yml
Fix bad hosts blocked/unblock domains variables.
=> Fix blocked/unblock domains

changelog/items/other/remove-helper-container.md, scripts/lib/ansible-executor.sh
Executing Ansible playbooks keeps stopped `alpine` helper containers. This PR removes the helper container after its run.
=> Remove helper container

.gitignore, changelog/items/key-updates/add-pinner-service.md, playbooks/group_vars/webportals.yml, playbooks/templates/.env.j2
Add pinner service modules flags
=> Add pinner service

playbooks/tasks/portal-configs-load.yml, playbooks/templates/.env.j2
=> Add Pinner configuration when Pinner is enabled.

playbooks/tasks/portal-send-funds.yml
=> Add alert suppress for sending funds to prevent failed command

playbooks/tasks/portal-docker-services-start.yml
Building docker compose images during deploys from cache (with `nocache: False`) builds outdated commit of branch or tag if new commits were done on the branch or a tag was moved.
This PR disables building from cache.
=> Fix deploying latest commit of (skyd) branches

playbooks/templates/.env.j2
* Adds & describes env variables added by https://github.com/SkynetLabs/webportal-nginx/pull/17
=> Add ACCOUNTS_REDIRECT_* env variables in .env.j2 template

playbooks/tasks/ansible-repo-version-get.yml
Git updated security handling and we need to adjust to it so we can run git commands from Ansible Control Machine.
=> Handle updated git security

playbooks/group_vars/webportals.yml, playbooks/tasks/portal-role-task-certbot-custom-dns.yml, playbooks/tasks/portal-role-task-certbot-setup-cloudflare.yml, playbooks/tasks/portal-role-task.yml
Add automation for cloudflare DNS.  Steps defined here:
https://github.com/SkynetLabs/skynet-webportal/blob/master/docker-compose.yml#L58
=> Add automation for cloudflare dns

playbooks/templates/.env.j2
Some of the abuse fields are duplicates. This PR makes them optional by pulling the already defined values.
=> update abuse settings to make them more optional

playbooks/tasks/portal-versions-set.yml
Portal setup fails with current docker override default value.
This PR is a fix for that.
=> Fix docker overrides environment default value

playbooks/portals-block-unblock-incoming-traffic.yml, playbooks/portals-set-vm-max-map-count.yml, playbooks/portals-setup-following.yml, playbooks/portals-setup-initial.yml, playbooks/portals-setup-ufw.yml, playbooks/tasks/secrets-storage-check-hosts-ini-update.yml, playbooks/x-portals-block-tor-exit-nodes.yml, playbooks/x-portals-ensure-latest-docker.yml, playbooks/x-portals-setup-dev-tools.yml, playbooks/x-portals-setup-disable-swap.yml, playbooks/x-portals-setup-serverlist.yml, playbooks/x-secrets-storage-migraton-wizard.yml
Playbooks v2 require the updated `hosts.ini` file in `ansible-private` repository.
This PR adds a check that `hosts.ini` was updated.
=> Add check that hosts.ini was updated for playbooks v2

playbooks/x-secrets-storage-migraton-wizard.yml
Move hosts.ini update for playbooks v2 check up in the playbook,
so that it fails earlier if the hosts.ini was not updated.
=> Move host.ini check up

playbooks/tasks/portal-role-task-mongo-replicaset-get-primary.yml
=> Fix splitting a string

playbooks/tasks/ansible-repo-version-get.yml
Minor bug in that if someone checks out a tag, the ansible logging fails because the git command doesn't handle a detached HEAD state.
=> handle git tags and git branches

playbooks/tasks/portal-docker-services-start.yml
=> Fix creating test user
