playbooks/tasks/host-limit-check.yml

Main update:
`ansible_play_hosts` was changed to `ansible_play_hosts_all`,
otherwise host limit check doesn't stop the playbook if some hosts are unreachable.

Fix host limit check for cases when some hosts are unreachable

---

playbooks/tasks/portal-docker-services-start.yml

Current waiting for Nginx not restarting doesn't seem to work correctly/always.
Waiting for Nginx not restarting was moved later in the task, so that Nginx has time to restart and we can catch it.

Move waiting for nginx restarting check later

---

README.md
playbooks/portals-deploy.yml

Till now we have performed deployments sequentially (rolling updates) one server at a time.
This PR adds an optional variable `parallel_deploys` that can set number of servers to deploy to in parallel.

Add variable to set number of parallel deployments

---

playbooks/group_vars/webportals.yml

LastPass server is using `\` instead of `/` between some shared folder levels.
This PR updates Ansible LastPass dirs to keep using just `/`.

Update LastPass dirs to fix backslashes in server paths

---

changelog/items/bugs-fixed/missing-server-config-fix.md
playbooks/tasks/portal-role-task.yml

Fix for setting default portal config values issue when portal config was not yet saved in secrets backup (LastPass).

Fix not yet saved portal config empty value

---

changelog/items/bugs-fixed/health-check-cli.md
changelog/items/bugs-fixed/out_of_lb_message.md
changelog/items/bugs-fixed/takedown-script-user.md
changelog/items/key-updates/parallel-deploys.md
playbooks/tasks/portal-health-check-disable.yml
playbooks/tasks/portal-health-check-enable.yml
playbooks/tasks/portal-health-checks-run.yml

The default case for the `out_of_lb_message` being blank was not being handled. This defines a variable as a helper as well.
Also updated the syntax for how the health check cli is called based on this PR <https://github.com/SkynetLabs/skynet-webportal/pull/1179> from @kwypchlo 
This error would case the deploy script to fail. Not it passes that error condition.

Fix bugs in deploy script

---

changelog/items/key-updates/wait-for-uploads.md
playbooks/group_vars/webportals_dev.yml
playbooks/group_vars/webportals_prod.yml
playbooks/tasks/portal-health-check-disable.yml

Switch out simple sleep with active uploads check for disabling health check.

Switch out sleep with uploads check for disable health check

---

playbooks/tasks/portal-health-check-disable.yml

Currently, when sia container is running, we wait and fail waiting for uploads.
This PR stops waiting for uploads when sia container is not running.

Fix waiting for uploads when sia container is not running

---

changelog/items/other/docker-start-timestamp.md
playbooks/tasks/portal-docker-services-start.yml

This PR add printing timestamp just before starting docker services.

Print timestamp before starting docker services

---

changelog/items/other/tighten-ufw-local-networks.md
playbooks/group_vars/webportals.yml
playbooks/tasks/portal-firewall-ufw-setup.yml

This PR tightens allowed outgoing traffic to local network rules by UFW firewall.
From local networks we only allow `10.10.10.0/24` used by portal docker services, the rest of the networks are denied.

Tighten allowed outgoing traffic by ufw rules

---

changelog/items/other/voting-members-majority-check.md
playbooks/portals-deploy.yml
playbooks/portals-restart.yml
playbooks/portals-rollback.yml
playbooks/portals-takedown.yml
playbooks/tasks/portal-mongo-replicaset-check-majority.yml
playbooks/tasks/portal-role-task-mongo-check-docker-service.yml
playbooks/tasks/portal-role-task-mongo-shell-eval.yml
playbooks/tasks/portal-stop.yml

Currently there is a risk that we stop portal mongo services during deploys, takedowns, etc. and there will be only 50% or less of MongoDB voting members online, which will disrupt portal operation.
This PR adds a check before stoping mongo service to be sure we keep > 50% MongoDB voting members online during execution of our playbooks.

Add check for keeping MongoDB replicaset majority online

---

changelog/items/other/increase-docker-down-timeout-for-mongo-primary.md
playbooks/tasks/portal-docker-services-stop.yml

Increase docker compose down timeout so that there is enough time for MongoDB primary node to step down.

Increase docker compose down timeout for mongo primary to step down

---

changelog/items/other/confirm-mongo-db-reset.md
playbooks/group_vars/webportals.yml
playbooks/tasks/portal-role-task-mongo-setup-docker-service.yml

Playbook `portal-setup-following` deletes and resets MongoDB database when it doesn't run correctly (e.g. the playbook can't connect to Mongo shell using defined admin credentials).
This PR asks user if it is ok to delete, reset MongoDB database or if he wants to fix it manually e.g. in case there are production data in the database.

Ask user before deleting mongo database

---

changelog/items/key-updates/disable-if-low-disk-space.md
playbooks/group_vars/webportals.yml
playbooks/tasks/portal-health-check-enable.yml
playbooks/templates/portals-status.json.j2

When free disk space is below the limit we do not want to enable health checks during deploys or restarts, we set or keep the portal disabled.

Disable portals if free disk space is below the limit

---

playbooks/tasks/portal-stop.yml
playbooks/templates/portals-status.json.j2

Fix for low disk reporting failure to Discord.
Add a flag to clean `renter.log` (defaults to false).

Fix discord reporting

---

changelog/items/other/discord-env-vars.md
playbooks/templates/.env.j2

When (`DISCORD_MENTION_ROLE_ID` was defined but) `DISCORD_MENTION_USER_ID=` was empty, `health-checker.py` script didn't report anything to discord.
This is the fix to not generate these two vars in `.env` file if their values are not defined.

Fix discord vars

---

playbooks/portals-block-skylinks.yml

Update skylinks block script:
- Set `host_pinned` strategy so that blocking is fast but doesn't clogg the execution.
- Allow empty blocklist to enable trigger just blocking from Airtable.

Skylinks block performance

---

README.md
playbooks/portals-stop.yml
scripts/portals-stop.sh

Simplying pulling out the portal stop task to be executed as a single play. Helpful for migrations.

Add helper for shutting down a portal

---

playbooks/tasks/portal-health-check-disable.yml

Added a condition to catch if the docker container is restarting when checking for uploads and downloads that are in progress.

Fix bug in checking for uploads and downloads

---

playbooks/portals-deploy.yml

For host limit check, we can't use `webportals_prod` now, because this group might not be defined (e.g. in pro portal inventory).

Fix host limit check for portals-deploy

---

playbooks/group_vars/webportals.yml

For new portals 100KS is too high of an initial allowance. Lowering the default in ansible to 10KS. 
I'm not putting this in the config since I don't think it is necessary out the gate for portal operators to be thinking too much about their allowance settings. Messing around with the allowance usually always causes more issues than it's worth.

Lower default allowance from 100KS to 10KS

---

playbooks/tasks/portal-health-check-disable.yml

Noticed a small edge case when disabling the health-check fails due to the container restarting. This shouldn't cause the ansible playbook to fail because the end result is that the health-check isn't running which is the goal.

fix bug in health-check disable

---

playbooks/templates/.env.j2

BLOCKER_HOST and BLOCKER_PORT are not user configurable and should just be configured in docker-compose file
requires https://github.com/SkynetLabs/skynet-webportal/pull/1573

remove not configurable variables

---

playbooks/tasks/portal-status-get-status.yml
playbooks/templates/portals-status.json.j2

Update getting portal status (to work with authenticated only portals):
- Get portal status using health checks.
- If health checks already run during deploy or restart - do not run them again.

Update getting status to run health checks

---

playbooks/group_vars/webportals.yml

Missing `s3_backup_path` in common or cluster config in LastPass is causing issues for new portal operators.
This PR sets it default empty value.

Set default S3 backup path

---

playbooks/tasks/portal-docker-prune-old-data.yml
playbooks/tasks/portal-docker-services-start.yml
playbooks/tasks/portal-role-task.yml

- completely drop pruning docker data **before** rebuilding containers - we want to leverage build cache to speed up the process
- **after** rebuilding, prune only docker data that is more than 4 hours old (arbitrary number but should be good enough) which means it will keep docker data that was produced during current build process
Originally we added strict pruning before and after because we were running out of disk space during deploys due to issues with cache, small disks on some machines, log files overflow etc. Also with every rebuild, docker data kept growing and I didn't know there was an option to prune just old data. I think we're in a quite good position to keep just current docker data now and it should significantly improve build times on deploys.
Let's test it @firyx :)

do not prune current docker data

---

my-vars/config-sample-do-not-edit.yml
playbooks/templates/.env.j2

Since our DB is cluster-wide, we don't need to backup each server individually. Moreover, the backup and restore scripts were not written to work with individual backups. That's why I'm changing the default path to be a common `mongo` dir under the S3 bucket.
PS: Sorry for the changed whitespaces - my editors are cleaning those up automatically, so I would have needed to add them back manually in order to reduce the size of the PR.

Change the S3 backup dir from per-server to one common dir.

---

changelog/items/other/ansiblecm-stop.md
changelog/items/other/lastpass-login-no-restart.md
changelog/items/other/parallel-dirs.md
scripts/ansiblecm-stop.sh
scripts/lastpass-login.sh
scripts/lib/ansible-executor.sh

This PR fixes some playbooks operations issues:
- Login to LastPass now doesn't restarts Ansible CM container (running playbooks e.g. deploys are not affected by LastPass login).
- Running parallel playbooks from different Ansible playbooks directories (e.g. regular and skynetpro.net) on the same machine are allowed (no need to stop the other directory Ansible CM container).

Parallel dirs

---

playbooks/x-portals-setup-serverlist.yml

Script setting serverlist used `SIA_API_PASSWORD` stored in a file, while skyd was updated to get the value from `.env` file.
This PR removed obsolete and incorrect setting of this variable.

Remove obsolete Sia API password setting from serverlist script

---

changelog/items/bugs-fixed/reset-ssh.md
playbooks/portals-setup-following.yml

When running `portal-setup-following` after `portal-setup-initial` we often get issues with Ansible become password (password not valid).
Debugging showed, that password is correctly read from LastPass and set in the playbook, manual login with the password succeeds.
I suspect that the issue is caused by Ansible multiplexing SSH connections (together with user switching done by playbooks), so I try to fix this by resetting SSH connection during playbook execution.
With this change I couldn't repeat the issue previously encountered on freshly set/reset host, so it might have been solved by this PR.

Fix Ansible become/sudo issues

---

README.md
changelog/items/key-updates/remove-cs-sync-block.md
playbooks/tasks/portal-docker-services-start.yml
playbooks/tasks/portal-role-task.yml

This PR removes the consensus being synced as a blocker in the `portals-setup-following`. The rational is that after setup-following you still need to send siacoins to the wallet and wait for contracts to form anyways. Additionally there is nothing in the remainder of setup-following that requires the consensus to be synced.
Instead, the consensus sync check has been added to the docker services start task so that we ensure consensus is synced at the end of a deploy. 

Remove Consensus Sync Block from Setup Following

---

changelog/items/key-updates/allowance-updates.md
playbooks/group_vars/webportals.yml
playbooks/tasks/portal-role-task.yml

Added `max_contract_price` and `max_sector_access_price` to default allowance settings based on discord discussion.

Add max contract and sector access prices to defaults

---

changelog/items/bugs-fixed/personal-laspass-handling.md
playbooks/group_vars/webportals.yml
playbooks/portals-setup-following.yml
playbooks/tasks/lastpass-load-json-note.yml
playbooks/tasks/lastpass-load-webportal-config.yml
playbooks/tasks/lastpass-load-yaml-note.yml
playbooks/tasks/lastpass-save-user-credentials.yml
playbooks/tasks/lastpass-save-webportal-config.yml

This PR adds handling of the different path separators for LastPass directories between shared folders and personal folders. Since shared folders have the prefix `Shared`, we can easily set the separator based on the top level folder name.
Terminal Output proof:
https://hackmd.io/so0iuxfgQxe2mQwhasrB8Q

Add handling for different path separators for lastpass

---

changelog/items/key-updates/tor-traffic.md
my-vars/config-sample-do-not-edit.yml
playbooks/group_vars/webportals.yml
playbooks/portals-setup-following.yml
playbooks/tasks/portal-firewall-iptables-block-tor-exit-nodes.yml
playbooks/templates/tor-blocklists-update.sh.j2
playbooks/x-portals-block-tor-exit-nodes.yml

This PR updates a playbook to block Tor exit nodes traffic and updates `portal-setup-following` to use new Tor traffic blocking task. Default option is to block Tor traffic, operators can opt out.

Tor blocklist cron

---

playbooks/tasks/portal-role-task.yml

Fix missing `become` for fixing elasticsearch container data permissions.

Fix missing become when fixing elasticsearch data directory permissions

---

playbooks/tasks/portal-firewall-iptables-block-tor-exit-nodes.yml

Ensure `skynet-webportal/scripts` directory exists on fresh server for uploading Tor blocking cron script.

Ensure scripts directory for Tor block script exists on fresh server

---

changelog/items/other/parallel-setups.md
playbooks/portals-setup-following.yml

Enable to run `portals-setup-following` in parallel using `parallel_setups` variable.

Enable parallel execution of portal-setup-following

---

changelog/items/bugs-fixed/wallet-seed-init.md
playbooks/tasks/portal-role-task.yml

There were two bugs in the wallet init with seed flow.
First, Sia requires the blockchain to be synced for the wallet to be initialized with the seed. I think this ultimately needs to be first in Sia, but for the time being I added the consensus sync wait so that we at least error because of the right reason. Previously it would error for another unlock check.
Second, I updated the check for if the seed is defined as it was incorrectly thinking it was. 

Fix wallet init with seed flow

---

changelog/items/bugs-fixed/lastpass-personal-yml-load-bug.md
playbooks/tasks/lastpass-load-json-note.yml
playbooks/tasks/lastpass-load-yaml-note.yml

There was a bug in accessing the LastPass personal yml files.
The `community.general.lastpass` tool was escaping characters differently than the `lpass` cmd. So this PR standardizes the use of `lpass` and updates the parsing of the variable fields. 

fix personal lastpass handling

---

playbooks/tasks/portal-firewall-iptables-block-tor-exit-nodes.yml

The current `portals-setup-following` script would throw errors due to the updates to the cronjob handling. This addresses those errors by updating the folder that they are downloaded to during setup. 

Move cron script to devops folder to avoid path errors

---

changelog/items/other/failed-when-setup-following.md
playbooks/portals-setup-following.yml

In `portals-setup-following` we have code to gracefully shut down docker if it is running. This is so that we can rerun the script on portals to update settings. 
We used `ignore_errors: True` on two tasks that could fail if docker isn't set up, i.e. a new portal. This allowed us to check the results in subsequent tasks to determine if we needed to do anything. 
`ignore_errors` still prints out the error in the ansible logs, so users were getting alarmed and confused when they would see the red errors from these tasks when setting up their portals. 
By switching to `failed_when: False` we achieve the same result but with no red error log. This just required updating the following task to look at the errors from these tasks rather than the failed result. 
Review and complete the checklist …

Switch ignore_errors to failed_when in setup following

---

README.md
changelog/items/other/parallel-setups.md
changelog/items/other/setup-and-deploy.md
playbooks/portals-deploy.yml
playbooks/portals-send-funds.yml
playbooks/portals-setup-following.yml
playbooks/portals-update-allowance.yml
playbooks/tasks/portal-deploy.yml

This PR adds an option to perform portal deployment at the end of `portals-setup-following`.
It is controlled by an optional `deploy_after_setup` variable.
By default (if the above variable is missing) deployment is not performed.
Also note that `parallel_deploys` variable was renamed to `parallel_executions`

Add option to include deployment during portal setup

---

changelog/items/bugs-fixed/iptables-after-docker.md
playbooks/portals-setup-following.yml

Fix issue when we want to set iptables rules for `DOCKER-USER` chain before docker is installed.

Set iptables rules after docker is installed

---

README.md
playbooks/portals-set-allowance-max-storage-price.yml
playbooks/portals-set-allowance-price-controls.yml
playbooks/tasks/lastpass-load-webportal-config.yml
scripts/portals-set-allowance-price-controls.sh

**Problem:** 
`max-contract-price` and `max-sector-access-price` are only set on server creation and cannot be adjusted via ansible scripts after that.
**Solution:**
Expand `set-allowance-max-storage-price` to also set `max-contract-price` and `max-sector-access-price`.
If this is not the way we want to approach this, we can always close this PR.

Expand set-allowance-max-storage-price 

---

changelog/items/key-updates/portal-modules-hosts-ini.md
playbooks/group_vars/webportals.yml

More variable consolidation. Now we can define the portal_modules in hosts.ini so that we don't need to be interacting with LastPass.
Updated here: https://github.com/SkynetLabs/ansible-private-sample/blob/main/inventory/hosts.ini#L58

Add portal_modules variable that can be defined in hosts.ini

---

playbooks/tasks/lastpass-save-cluster-config.yml

Fix a bug in selecting last cluster config LastPass path for saving cluster config.

Fix getting last config LastPass path

---

changelog/items/bugs-fixed/dict-difference.md
playbooks/tasks/dictionary-diff.yml
playbooks/tasks/lastpass-save-cluster-config.yml
playbooks/tasks/portal-versions-rollback-config-files.yml

There is a bug in `difference()` that really makes it so that it frankly just doesn't work, which is wild.
https://stackoverflow.com/questions/40115323/calculate-set-difference-using-jinja2-in-ansible
So I created a manual difference checker for dictionaries. While I was at it I was able to have the difference printed out be the `key: value` instead of just the `key`
Prints out like the following
```
MSG:
Dictionary Difference:
Original Values
portal_modules: absu
New Values
portal_modules: abs
field1: test
```

Add custom difference dict task

---

playbooks/tasks/portal-role-task.yml

Running setup-portal-following will execute "prunning old docker data" which means that if we run a deploy on a machine, it will remove all docker data older than 4 hours from that machine and following deploy playbook will not take advantage of any cached builds. This is why we removed pruning the docker data step directly before the build step.

do not prune docker data in portal-role-task

---

playbooks/tasks/portal-docker-services-stop.yml

prevent situations like
> Found orphan containers (abuse) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.

remove orphans when stopping

---

changelog/items/other/no-wait-for-restarting-sia.md
playbooks/tasks/portal-health-check-disable.yml

When disabling health checks (e.g. when executing takedown playbook) we wait for uploads and downloads to finish. This expects `sia` container to be running. This PR skips waiting (fixes an issue) when sia container is restarting.

Do not wait for uploads/downloads when sia is restarting

---

changelog/items/bugs-fixed/fix-devops-dir-permissions.md
playbooks/group_vars/webportals.yml
playbooks/tasks/portal-firewall-iptables-block-tor-exit-nodes.yml

On fresh server, `devops/scripts` dir was created with root permissions, causing issues later. This PR fixes the permissions.
Already tested on a fresh portal.

Fix devops permissions

---

changelog/items/key-updates/docker-image-overrides.yml
my-vars/config-sample-do-not-edit.yml
playbooks/group_vars/webportals_pro.yml
playbooks/tasks/portal-versions-set.yml

This PR adds the ability to override multiple docker images when defined in the following format:
```yml
docker_image_overrides:
- { service: "website", image: "skynetlabs/website-skynetpro-net" }
- { service: "blocker", image: "skynetlabs/blocker" }
```
Additionally, the default image override for the websites was added for the pro cluster. This pulls from the hosts.ini file in the ansible private repo where I added children to the pro cluster for skynetpro and skynetfree, to define their specific image variables.
https://github.com/SkynetLabs/ansible-private/blob/master/inventory/hosts.ini#L122

Add ability to override docker images

---

playbooks/portals-block-unblock-incoming-traffic.yml
playbooks/portals-deploy.yml
playbooks/portals-set-vm-max-map-count.yml
playbooks/portals-setup-following.yml
playbooks/portals-setup-initial.yml
playbooks/portals-setup-ufw.yml
playbooks/x-portals-block-tor-exit-nodes.yml
playbooks/x-portals-ensure-latest-docker.yml
playbooks/x-portals-setup-dev-tools.yml
playbooks/x-portals-setup-disable-swap.yml
playbooks/x-portals-setup-serverlist.yml

Turns out ansible handles undefined vars files differently based on if `gather_facts` is true or false.
When it is false, it doesn't care if the vars_files are defined
When it is true, it will error.
Defining the `vars_files` as an array allows ansible to load any that are defined, as long as one is defined. I added the `common_vars_file` to the ansible-private-sample repo to make it a required variable so it is always defined.
https://github.com/SkynetLabs/ansible-private-sample/pull/3
This makes sense as we can then work on moving all custom variables to these custom var files and out of hosts.ini and the `my-vars` directory in this repo. 

Update vars_files definitions

---

changelog/items/other/handle-torproject-exitnodelist-outage.md
playbooks/templates/tor-blocklists-update.sh.j2

This PR fixes 2 issues when official Tor Project Exit Node List service has outage:
- we can't deploy, because deploy script fails checking Tor blocking script before adding it to cron
- cron job fails and doesn't downloads/updates the second, unofficial Tor blocklist

Sky 315 handle torproject exitnode outage

---

playbooks/portals-run-health-checks.yml
playbooks/tasks/portal-configs-load.yml
playbooks/tasks/portal-deploy-enable-loadbalancer.yml
playbooks/tasks/portal-health-checks-run.yml
playbooks/tasks/portal-integration-tests-run.yml
playbooks/tasks/portal-set-module-flags.yml

portal_modules updated didn't handle empty lastpass values correctly since the flags were still being set off of the webportal config values. 
refactored and fixed for clarity. 
Add sleep back in before running tests and enabling the server.
Fix retries for the tests as they weren't actually triggering. oops.

Fix bug with empty portal_modules in lastpass

---

playbooks/tasks/portal-integration-tests-run.yml

- use node lts (long term support) release to make sure we're using skynet-js supported node version (for example current lts is 16 and latest is 18 and if node releases 19 skynet-js could break until fixed so we want to lag behind a bit)
- use `--no-cache` in `apk add` as it's recommended
- use `--single-branch --depth 1` to fetch just one branch (clones the repo faster)
- use `--frozen-lockfile` on `yarn` to make sure yarn doesn't need to check for versions during install, only installs what's in lockfile

clean up integration tests command

---

playbooks/templates/.env.j2

Because rewriting "takedown" feature to be backwards compatible would be almost impossible, I introduced new variable that you can pass in hosts.ini that replaces takedown functionality. Takedown should become deprecated after this is merged.
Example usage in hosts.ini:
```ini
[webportals_siasky]
...
as-hk-1 ansible_host=as-hk-1.siasky.net
as-sp-1 ansible_host=as-sp-1.siasky.net
as-sp-2 ansible_host=as-sp-2.siasky.net deny_public_access=true
eu-fin-1 ansible_host=eu-fin-1.siasky.net
...
```
Once this is merged, we should rewrite our infrastructure's hosts.ini takedown into deny_public_access.

support deny_public_access as a replacement for takedown

---

playbooks/tasks/portal-docker-services-stop.yml

Stopping docker services is expected to fail in some cases (e.g. during the first execution of `portals-setup-following`) and we ignore the error, but it is logged in red color in Ansible logs, which scares portal operators.
This PR removes red error from Ansible logs.

Remove ignored red error from Ansible log

---

playbooks/tasks/ansible-repo-version-get.yml
playbooks/tasks/portal-accounts-generate-jwks.json.yml
scripts/lib/ansible-executor.sh

Fix for generating `jwks.json` using `oathkeeper` image oneliner.
There was an issue generating it using `docker_container` ansible module so it was replaced with command ansible module.
For this ansibleCM image had to be updated with installed docker package.

Fil/sky 1327 fix jwks.json generation

---

playbooks/group_vars/webportals.yml
playbooks/tasks/portal-role-task.yml
playbooks/templates/.env.j2

This PR extends the `portal-role-task.yml` file with an extra step that pulls the `cypress` image. This avoids having to pull it on request when the abuse scanner needs it, ensuring a smooth parse of the abuse email rather than hanging for x seconds waiting on the image being pulled.
It also adds support for the `ABUSE_TMP_DIR` env. variable.
N/A
Closes SKY-730

Pull `cypress` image

---

playbooks/group_vars/webportals.yml
playbooks/tasks/portal-integration-tests-run.yml

use existing `skynet_js_docker_test_image` variable to store skynet-js node image version

use variable to store skynet-js node image version

---

playbooks/tasks/portal-update-allowance.yml

Speed up the playbook on some servers from couple of minutes to less than a minute.
The renter output is around 15M in size so passing it as a whole probably takes a lot of time, preprocessing it and extracting smaller pieces of the json helps a lot.

Parse renter as json before using it

---

playbooks/group_vars/webportals.yml
playbooks/tasks/portal-role-task.yml

- removes all logrotate.d configurations prefixed with "skynet-webportal-" (prune old ones before copying over new ones)
- copy over all logrotate config files from skynet-webportal repo (ignore errors if running on old version of skynet-webportal that does not have those defined yet)

setup logrotate configuration for webportal services

---

playbooks/tasks/portal-role-task.yml

* is being badly expanded for some reason and we end up with error, we need to use different syntax to copy over all files in directory

fix cp files

---

playbooks/group_vars/webportals.yml
playbooks/tasks/portal-logs-clean-renter-log.yml
playbooks/tasks/portal-stop.yml

Added workaround for renter accounting issue on deploy in playbooks/tasks/portal-stop.yml. When number of workers on cooldown on a server before deploy exceeds 100, after sia is down we're deleting renter/accounts.dat file (it is recreated on startup) which temporarily resolves the issue. 
Minor changes:
- created sia data directory variable "sia_data_dir"
- created a generic variable for multi purpose alpine docker image "alpine_image" (updated to latest)
- removed redundant step "Pull Alpine image" - when using an image with "community.docker.docker_container" it will be pulled anyway if its not locally available
- removed "container_default_behavior" key from "community.docker.docker_container" usage since "no_defaults" is the default anyway
✅  tested on servers with and without renter …

Insufficient balance workers issue workaround

---

playbooks/tasks/portal-role-task.yml

Turns out command `rm -f /etc/logrotate.d/skynet-webportal-*` did not work as expected (asterisk was evaluated against local shell) and no files were deleted and the subsequent command that copies files does not overwrite files so once files were copied, they were not updated. This pull request changes the way we delete existing logrotate config files from host to be more reliable.
✅ Tested on dev servers and already deployed with on pro/free servers.

delete old logrotate files before copying new ones
